version: '3'
services:
  spring-app:
    image: spring-app
    container_name: "spring-app-container"
    restart: always
    build: .
    ports:
      - "9090:8080"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
      MYSQL_PORT: 3306

  db:
    image: mysql:8.0.33
    container_name: "mysql-container"
    volumes:
      - dbbase:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: senha
      MYSQL_DATABASE: kube
volumes:
  dbbase:
